commerce_payment.commerce_payment_gateway.plugin.stripe:
  type: commerce_payment_gateway_configuration
  mapping:
    publishable_key:
      type: string
      label: 'Publishable key'
    secret_key:
      type: string
      label: 'Secret key'
    enable_credit_card_icons:
      type: boolean
      label: 'Enable credit card icons'
commerce_payment.commerce_payment_gateway.plugin.stripe_payment_element:
  type: commerce_payment_gateway_configuration
  mapping:
    publishable_key:
      type: string
      label: 'Publishable key'
    secret_key:
      type: string
      label: 'Secret key'
    payment_method_usage:
      type: string
      label: 'Payment method usage'
    style:
      type: mapping
      label: 'Style'
      mapping:
        theme:
          type: string
          label: 'Theme'
        layout:
          type: string
          label: 'Layout'
    checkout_form_display_label:
      type: mapping
      label: 'Checkout form display label'
      mapping:
        custom_label:
          type: string
          label: 'Custom display label'
        show_payment_method_logos:
          type: string
          label: 'Show payment method logos?'
        include_logos:
          type: sequence
          label: 'Logos to include'
          sequence:
            type: string
